server:
  port: 8083

spring:
  application:
    name: shipment-service
  datasource:
    url: jdbc:h2:mem:shipmentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: false
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: ${JWT_SECRET:SmartLogixSuperSecretKeyForJWT2024PlatformMicroservicesArchitecture!!}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
